### ISSUE TITLE
Expanding top-level header expands all subheaders

### ISSUE THREAD

**Issue by adacosta92** [ofdiceandmagic/FVTT-collapsible-journal-sections#11]
It'd be nice to navigate to a subsection through expanding h1, then finding which header 2 (h2) to expand, then which header 3 (h3) to expand after, and so on. Especially useful with very large journal entries where I'm trying to navigate to the middle somewhere.

When expanding a header, keeping all subheaders under it collapsed would solve this.

**Comment by ofdiceandmagic** [comment]
This is a great idea. 
Added to my todo list

**Comment by Shuggaloaf** [comment]
Just wanted to second this.  

Mod is already great and is helping me condense so much info that was previously in separate entries. Adding that feature would make this mod perfect!

**Comment by ofdiceandmagic** [comment]
This feature has been added in the latest update, v 1.3.0.

Thanks so much for the feedback!

**Comment by Shuggaloaf** [comment]
Wow that was quick turn around! 

You're welcome for the feedback. Thank YOU for your effort! :-)
