### ISSUE TITLE
Auto collapse only works inside the secret tag

### ISSUE THREAD

**Issue by rinnocenti** [ofdiceandmagic/FVTT-collapsible-journal-sections#13]
In my journals the paragraphs that are outside the secrets tag do not open, (when set to start closed)
When I put them inside the secrets tag they work.
other things, sometimes in the edition when the text is collapsed it doesn't open inside the edition so it erases all the text that is not being displayed.

**Comment by rinnocenti** [comment]
[fvtt-JournalEntry-Facções.zip](https://github.com/ofdiceandmagic/FVTT-collapsible-journal-sections/files/6502965/fvtt-JournalEntry-Faccoes.zip)

**Comment by ofdiceandmagic** [comment]
Hi, sorry you're having this problem?

Please check that the module is updated and let me know if it keeps happening.

**Comment by rinnocenti** [comment]
updated module and the problem continues.

**Comment by ofdiceandmagic** [comment]
Sorry, I have been unable to reproduce the issue. If anyone else reports the same issue, I'll look into it further.
