### ISSUE TITLE
Module not working in some Game Worlds

### ISSUE THREAD

**Issue by MrBrentRogers** [ofdiceandmagic/FVTT-collapsible-journal-sections#5]
Just installed the module and haven't been able to get it to work on an existing world.
Tested:

creating a new Journal entry - still nothing. Clicking on titles just highlights them.
restarting world
restarting Foundry
Set Default Collapsed State to Collapsed - nothing.

Just add that it is working in other worlds, just not my main world

I wonder if its because of drag and dropped actor/scene/item links

**Comment by Arcainne** [comment]
Not working for me either. There are a few places where a null check might fix these issues (two I found below, but I saw more).
```
Uncaught (in promise) TypeError: Cannot read property 'nodeName' of null
    at get_h (cjs.js:163)
```
```
Uncaught (in promise) TypeError: Cannot read property 'nextElementSibling' of null
    at apply_default_classes_and_state (cjs.js:71)
```

**Comment by TheBiggerBadderWolf** [comment]
Not working for me either unfortuantely. I'm using the Degenesis System (https://github.com/moo-man/DEGENESIS-FoundryVTT) which edits CSS itself, and hosting on The Forge.

**Comment by ofdiceandmagic** [comment]
There have been significant updates today, let me know if this is still an issue.

**Comment by TheBiggerBadderWolf** [comment]
All working here now, great stuff thank you!

**Comment by ofdiceandmagic** [comment]
You're welcome!
